/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.panel;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class Almacen extends javax.swing.JPanel {

    DefaultTableModel model;
    DAO.DaoConectar cc = new DAO.DaoConectar();
    public Almacen() {
        initComponents();
        busqueda();
        data.setVisible(true);
        tabla.setVisible(false);
        try {
            Statement sent = cc.conexion().createStatement();
            ResultSet rs = sent.executeQuery("select *from Productos");
            while (rs.next()) {
                this.producto.addItem(rs.getString("nom_product"));
            }

        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        data = new javax.swing.JPanel();
        producto = new javax.swing.JComboBox<>();
        codigo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        tabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_ventas = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        data.setBackground(new java.awt.Color(255, 255, 255));
        data.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoActionPerformed(evt);
            }
        });
        data.add(producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 130, 30));
        data.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 60, 20));

        jButton1.setText("Resgistros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        data.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        jLabel1.setText("Cantidad:");
        data.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 60, 30));

        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });
        data.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 90, 30));

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        data.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 80, -1));

        add(data, "card2");

        tabla.setBackground(new java.awt.Color(255, 255, 255));
        tabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(t_ventas);

        tabla.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 530, 190));

        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        tabla.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        add(tabla, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoActionPerformed
        try {
            Statement sent = cc.conexion().createStatement();
            ResultSet rs = sent.executeQuery("select *from Productos where nom_product='" + this.producto.getSelectedItem() + "'");
            rs.next();
            codigo.setText(rs.getString("cod_productos"));
            

        } catch (SQLException e) {
        }
    }//GEN-LAST:event_productoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        data.setVisible(true);
        tabla.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        data.setVisible(false);
        tabla.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            DAO.DaoAlmacen.Guardar(cantidad.getText(), codigo.getText());
            busqueda();
        } catch (SQLException e) {
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed

    public void busqueda() {
        String[] titulos = {"CODIGO", "Total de Producto","Producto"};
        String[] registros = new String[50];
        String sql = "select cod_al,cantida_ini,nom_product from Almacen  inner join Productos on  Productos.cod_productos = Almacen.cod_productos ";

        model = new DefaultTableModel(null, titulos);
        try {
            Statement st = (Statement) cc.conexion().createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("cod_al");
                registros[1] = rs.getString("cantida_ini");               
                registros[2] = rs.getString("nom_product");               

                model.addRow(registros);
            }
            t_ventas.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }

    }
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidad;
    private javax.swing.JLabel codigo;
    private javax.swing.JPanel data;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> producto;
    private javax.swing.JTable t_ventas;
    private javax.swing.JPanel tabla;
    // End of variables declaration//GEN-END:variables
}
