/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.panel;

import DAO.DaoProductos;
import Reporte.ReportGenerator;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class Productos extends javax.swing.JPanel {

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
        busqueda();
        t_producto.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if (t_producto.getSelectedRow() != -1) {
                int fila = t_producto.getSelectedRow();
                ad = t_producto.getValueAt(fila, 00).toString();
                codigo.setText((t_producto.getValueAt(fila, 0).toString()));

            }
        });

    }
    DAO.DaoConectar cc = new DAO.DaoConectar();
    static String del;
    static String ad;
    DefaultTableModel model;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productos = new javax.swing.JPanel();
        nombre = new javax.swing.JTextField();
        costo = new javax.swing.JTextField();
        peso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        registros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_producto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        codigo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        productos.setBackground(new java.awt.Color(255, 255, 255));
        productos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        productos.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 110, 30));
        productos.add(costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 110, 30));
        productos.add(peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 110, 30));

        jLabel2.setText("NOMBRE :");
        productos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel3.setText("COSTO :");
        productos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel4.setText("PESO :");
        productos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        productos.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 80, -1));

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        productos.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 80, -1));

        jButton4.setText("Registros");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        productos.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 80, -1));

        add(productos, "card3");

        registros.setBackground(new java.awt.Color(255, 255, 255));
        registros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(t_producto);

        registros.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 440, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/search.png"))); // NOI18N
        registros.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });
        registros.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 110, 30));

        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        registros.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        registros.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 80, -1));

        jButton6.setText("Editar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        registros.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));
        registros.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 20, 20));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/PDF 2_26px.png"))); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);

        registros.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 50, 40));

        add(registros, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            DaoProductos.Guardar(nombre.getText(), costo.getText(), peso.getText());
            busqueda();
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            DaoProductos.update(nombre.getText(), costo.getText(), peso.getText(), codigo.getText());
            busqueda();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        productos.setVisible(true);
        registros.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        productos.setVisible(false);
        registros.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (t_producto.getSelectedRows().length > 0) {
            int fila = t_producto.getSelectedRow();
            String valor = t_producto.getValueAt(fila, 0).toString();
            int jaja = JOptionPane.showConfirmDialog(null, "Desea Eliminar este registro", "Registro eliminado", JOptionPane.YES_NO_OPTION);
            if (jaja == JOptionPane.YES_OPTION) {
                if (fila >= 0) {
                    try {
                        DaoProductos.eliminar(codigo.getText());
                        busqueda();
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Error " + ex);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccion la fila a eliminar");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jalar();
        registros.setVisible(false);
        productos.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        busqueda();        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        ReportGenerator re =new  ReportGenerator();//CREAMOS UN OBJETO DE LA CLASE REPORTES
        String ruta = "src/Jasper/ReporteProducto.jasper";//RUTA DONDE TIENEN SU REPORTE --
        //ABRIR CUADRO DE DIALOGO PARA GUARDAR EL ARCHIVO
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("todos los archivos *.PDF", "pdf", "PDF"));//filtro para ver solo archivos .pdf
        int seleccion = fileChooser.showSaveDialog(null);
        try {
            if (seleccion == JFileChooser.APPROVE_OPTION) {//comprueba si ha presionado el boton de aceptar
                File JFC = fileChooser.getSelectedFile();
                String PATH = JFC.getAbsolutePath();//obtenemos la direccion del archivo + el nombre a guardar
                try (PrintWriter printwriter = new PrintWriter(JFC)) {
                    printwriter.print(ruta);
                }
                re.resportesPDF(ruta, PATH);
                //mandamos como parametros la ruta del archivo a compilar y el nombre y ruta donde se guardaran
                //comprobamos si a la hora de guardar obtuvo la extension y si no se la asignamos
                if (!(PATH.endsWith(".pdf"))) {
                    File temp = new File(PATH + ".pdf");
                    JFC.renameTo(temp);//renombramos el archivo
                }
                JOptionPane.showMessageDialog(null, "Esto puede tardar unos segundos,espere porfavor", "Estamos Generando el Reporte", JOptionPane.WARNING_MESSAGE);
                JOptionPane.showMessageDialog(null, "Documento Exportado Exitosamente!", "Guardado exitoso!", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (FileNotFoundException | HeadlessException e) {//por alguna excepcion salta un mensaje de error
            JOptionPane.showMessageDialog(null, "Error al Exportar el archivo!", "Oops! Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    public final void busqueda() {
        String[] titulos = {"CODIGO", "PRODUCTO", "COSTO", "PESO"};
        String[] registros = new String[50];
        String sql = "select * from Productos where  est_prod = 'A' ";

        model = new DefaultTableModel(null, titulos);
        try {
            Statement st = (Statement) cc.conexion().createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("cod_productos");
                registros[1] = rs.getString("nom_product");
                registros[2] = rs.getString("costo_product");
                registros[3] = rs.getString("peso_product");

                model.addRow(registros);
            }
            t_producto.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }

    }

    public class Function {

        Connection con = null;
        ResultSet rs = null;
        PreparedStatement ps = null;

        public ResultSet find(String s) {
            try {

                ps = cc.conexion().prepareStatement("select * from Productos where cod_productos = ?  ");
                ps.setString(1, s);

                rs = ps.executeQuery();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            return rs;
        }

    }

    public void jalar() {
        Function f = new Function();
        ResultSet rs = null;
        rs = f.find(codigo.getText());
        try {
            if (rs.next()) {
                nombre.setText(rs.getString("nom_product"));
                costo.setText(rs.getString("costo_product"));
                peso.setText(rs.getString("peso_product"));

            } else {
                JOptionPane.showMessageDialog(null, "Error no se encuentra Usuario");
            }
        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codigo;
    private javax.swing.JTextField costo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField peso;
    private javax.swing.JPanel productos;
    private javax.swing.JPanel registros;
    private javax.swing.JTable t_producto;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
